// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchTaskInputs() {
  return window['go']['gui']['App']['FetchTaskInputs']();
}

export function InitUser() {
  return window['go']['gui']['App']['InitUser']();
}
