// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function FetchTaskInputs():Promise<Array<common.TimeTaskInput>>;

export function InitUser():Promise<any>;
