# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Quality Gate

on:
  push:
    branches: ["master"]
  # pull_request:
  #   branches: ["master"]
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Environment'
    #     type: environment
    #     required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    environment: default
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build Hybrid - Windows
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: b1-timetask-cli-go
          build-platform: windows/amd64

      - name: Test
        run: ./scripts/run-tests.sh
        env:
          COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}
