# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Quality Gate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and test
    environment: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: ./scripts/run-tests.sh
      env:
        COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}
        
        
